const products = [
  {
    id: 1,
    rank: "feature",
    image: "./img/Brands/Adidas/Lite Racer Adapt 6.0.webp",
    brand: "Adidas",
    title: "Lite Racer Adapt 6.0",
    price: 130,
  },
  {
    id: 2,
    rank: "feature",
    image: "./img/Brands/Adidas/Ultraboost 5X.webp",
    brand: "Adidas",
    title: "Ultraboost 5X",
    price: 170,
  },
  {
    id: 3,
    rank: "new",
    image: "./img/Brands/Adidas/Supernova Rise.webp",
    brand: "Adidas",
    title: "Supernova Rise",
    price: 140,
  },
  {
    id: 4,
    rank: "new",
    image: "./img/Brands/Adidas/Adifom Stan Smith Mule.webp",
    brand: "Adidas",
    title: "Adifom Stan Smith Mule",
    price: 80,
  },
  {
    id: 5,
    rank: "",
    image: "./img/Brands/Adidas/Samba XLG.webp",
    brand: "Adidas",
    title: "Samba XLG",
    price: 100,
  },
  {
    id: 6,
    rank: "",
    image: "./img/Brands/Adidas/SOLEZ.webp",
    brand: "Adidas",
    title: "SOLEZ",
    price: 110,
  },
  {
    id: 7,
    rank: "",
    image: "./img/Brands/Adidas/NMD_R1.webp",
    brand: "Adidas",
    title: "NMD_R1",
    price: 120,
  },
  {
    id: 8,
    rank: "",
    image: "./img/Brands/Adidas/Ultraboost 5.webp",
    brand: "Adidas",
    title: "Ultraboost 5",
    price: 160,
  },
  {
    id: 9,
    rank: "",
    image: "./img/Brands/Adidas/Gazelle.webp",
    brand: "Adidas",
    title: "Gazelle",
    price: 100,
  },
  {
    id: 10,
    rank: "",
    image: "./img/Brands/Nike/Air Jordan 3 Retro Cement Grey.webp",
    brand: "Nike",
    title: "Air Jordan 3 Retro Cement Grey.webp",
    price: 120,
  },
  {
    id: 11,
    rank: "feature",
    image: "./img/Brands/Nike/Luka 3 Speedway.webp",
    brand: "Nike",
    title: "Luka 3 Speedway",
    price: 170,
  },
  {
    id: 12,
    rank: "feature",
    image: "./img/Brands/Nike/Tatum 2 Legacy.webp",
    brand: "Nike",
    title: "Tatum 2 Legacy ",
    price: 150,
  },
  {
    id: 13,
    rank: "new",
    image: "./img/Brands/Nike/Air Jordan 4 RM.webp",
    brand: "Nike",
    title: "Air Jordan 4 RM",
    price: 130,
  },
  {
    id: 14,
    rank: "new",
    image: "./img/Brands/Nike/Nike Cortez Vintage Suede.webp",
    brand: "Nike",
    title: "Nike Cortez Vintage Suede",
    price: 140,
  },
  {
    id: 15,
    rank: "",
    image: "./img/Brands/Nike/Luka 3 Motorsport.webp ",
    brand: "Nike",
    title: "Luka 3 Motorsport",
    price: 170,
  },
  {
    id: 16,
    rank: "",
    image: "./img/Brands/Nike/Nike Air DT Max 96.webp",
    brand: "Nike",
    title: "Nike Air DT Max 96",
    price: 120,
  },
  {
    id: 17,
    rank: "",
    image: "./img/Brands/Nike/Nike Air Trainer SC High.webp",
    brand: "Nike",
    title: "Nike Air Trainer SC High",
    price: 100,
  },
  {
    id: 18,
    rank: "",
    image: "./img/Brands/Nike/Nike Dunk Low.webp",
    brand: "Nike",
    title: "Nike Dunk Low",
    price: 110,
  },
  {
    id: 19,
    rank: "",
    image: "./img/Brands/Nike/Nike SB Chron 2 Canvas.webp",
    brand: "Nike",
    title: "Nike SB Chron 2 Canvas",
    price: 125,
  },
  {
    id: 20,
    rank: "",
    image: "./img/Brands/Nike/Jordan 1 Mid SE.webp",
    brand: "Nike",
    title: "Jordan 1 Mid SE",
    price: 80,
  },
];
